# This workflow creates a branch from the translations/fi folder
env:
  
  LANG_CODE: fi

name: Finnish [FI] Translations

# Runs on push to master, only when files under `translations/fi` are modified
on:
  push:
    branches: [ master ]
    paths:
      - 'translations/${ env.LANG_CODE }/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'translations/${ env.LANG_CODE }/**'

jobs:
  build:
    name: Build [FI] Translations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Create branch from translations/${ env.LANG_CODE } folder
    - name: Create branch from language
      run: |
        git config --global user.email "dani@kedarastudios.com"
        git config --global user.name "GH Translation BOT"
        ./scripts/create-translated-branch.sh $LANG_CODE
        git push -f origin translations-$LANG_CODE:translations-$LANG_CODE
